# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'InstaUnfollower' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InstaUnfollower

  pod 'Google-Mobile-Ads-SDK'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'
  def available_pods
    # Pods for AppCenter
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'CodePush', :path => '../node_modules/react-native-code-push'   # <-- the only one added in this commit
    pod 'RNIap', :path => '../node_modules/react-native-iap'

  end

end
